### PR TITLE
adding a script for threading a sequence onto a structure

### PR DESCRIPTION
**Pull request by decarboxy**
In protein design a common task is to thread a sequence onto a template protein with no gaps and generate a full atom structure.  It turns out that AI models are an extremely time-efficient way to do this relative to other approaches. 

This PR implements this as a new script, called `thread_sequence.py`, which implements this type of threading. I wrote it as a separate script since it is a sufficiently different task from normal inference. In order to reduce code duplication, some of the functions used by both scripts were pushed into a new utility module. 

I also removed a bunch of code from the `__init__.py` files to resolve some odd import issues i was having.  The code in question shouldn't be necessary, if it's serving a specific purpose lemme know and i can figure out another approach.

Last, I'd really appreciate comments about the structure of this, I think there's probably a better way to organize it but im not seeing it right now

### CODE REVIEW

**Comment by gahdritz** [comment]
Sorry for the delay on this. Did the Docker build crash for no good reason (kind of looks like that's the case from the logs), or because of a change in this PR?

**Comment by gahdritz** [comment]
Ok looks like the build is passing now. If you could just remove the print statement in fb666d0 I'll merge.

**Comment by decarboxy** [comment]
@gahdritz Thanks! ive removed the excess print statement

**Comment by decarboxy** [comment]
having used this a bit in practice we're definitely going to want PDB input rather than MMCIF input for the template, going to tackle that in a followon PR

**Pull request merged**
