### PR TITLE
Fix Colab again after ModelCIF merge and python version change in Colab

### PR DESCRIPTION
**Pull request by vaclavhanzl**
Recent #284 merge broke the Colab notebook in two ways:
* added new dependency on modelcif (I'd say it's notebook's fault to get broken so easily)
* added required arguments cif_output (here I propose a slight change in the cif code)

This PR adds the modelcif dependency to Colab. For the new arguments, instead of adding them to the notebook, I rather made them optional in the cif output code as people may have an existing code which was also broken by the change. With optional arguments, things are easily made backward compatible.

In addition, Google Colab changed Python version to 3.9 and we absolutely must track this change in the tricky conda install in Colab. First I just changed 3.8 to 3.9 at four places in b95099b and then automated such changes for the future in 8b36691.

@josemduarte I slightly touched your recent code, just making some args optional, please check feb9993

### CODE REVIEW

**Comment by vaclavhanzl** [comment]
Yes, main was broken and I fixed it in #309 - please merge that first. Then tests will likely pass here, too.

**Comment by josemduarte** [comment]
> I slightly touched your recent code, just making some args optional, please check https://github.com/aqlaboratory/openfold/commit/feb99932b7cbc9c8d4882da3e8dcb2dc6061e2e9

Thanks, that looks good to me

**Comment by warrenalphonso** [comment]
Thanks for doing this. Could you merge this @gahdritz?

**Comment by vaclavhanzl** [comment]
I added one more commit to fix a recent openmm issue. See conversation in #286.
(I expect automatic commit tests to fail again as my PR #309 stays not merged yet, too.)

**Comment by vaclavhanzl** [comment]
@christinaflo Could you please merge this one as well? Thank you for merging #309. I forced test re-run here in 308 and yes, now it is all green! :)
Merging this will make prospective OpenFold users happy, as well as merging 309 was important to be nice to our PR contributors.

**Comment by gahdritz** [comment]
Awesome---thanks guys!

**Pull request merged**
