### PR TITLE
update loss logging and stop sampling recycling iterations in validation

### PR DESCRIPTION
**Pull request by lhatsk**
Fixes https://github.com/aqlaboratory/openfold/issues/56 
Fixes https://github.com/aqlaboratory/openfold/issues/51
Fixes OpenFoldBatchCollator: generator argument not properly set and stage ignored (defaulting to train) 

Edit: I just noticed that the generator argument is never used. Could be removed from OpenFoldBatchCollator

### CODE REVIEW

**Comment by gahdritz** [comment]
On second thought, rather than making a specific exception for training, I think it might be better to move this option out of the generic `supervised` section of the config, which is supposed to be common to training and validation, and add it as an option to the training-stage specific sections. So e.g. you'd have `self.config.train.uniform_recycling` and `self.config.eval.uniform_recycling`. What do you think?

**Comment by lhatsk** [comment]
Sounds good to me. Same for predict s.t. we can just match on stage_cfg.uniform_recycling?

**Comment by gahdritz** [comment]
Yeah sure

**Comment by lhatsk** [comment]
done

**Comment by gahdritz** [comment]
One more thing: the generator is actually unused in OpenFoldBatchCollator, so it would be better to just remove it as a parameter entirely.

**Pull request merged**
