### PR TITLE
Fix notebook: Colab now has python 3.8, fix imports, mitigate UTF-8 glitch

### PR DESCRIPTION
**Pull request by vaclavhanzl**
Make the colab notebook work (fix issue #286):

* Python 3.8 is now what we get in Colab, use it in our Conda as well
* Fix imports, make some unconditional - chain of depencencies makes them needed even for relax_prediction==False (overwrite_b_factors() comes from [file](https://github.com/aqlaboratory/openfold/blob/main/openfold/np/relax/utils.py#L40) which imports openmm)
* Mitigate spurious error "A UTF-8 locale is required. Got ANSI_X3.4-1968" which makes all shell commands defunct - use shutil.make_archive()
* In the second commit, mitigate the ANSI_X3.4-1968 problem yet much better, making %shell work again

The strange "ANSI_X3.4-1968" thing happens sometimes [not only to us](https://stackoverflow.com/questions/56081324/why-are-google-colab-shell-commands-not-working). When it happens, no shell commands work anymore. Likely [OpenMM is the culprit](https://github.com/sokrypton/ColabFold/issues/237). I used the same mitigation as [AlphaFold did for the same problem](https://github.com/deepmind/alphafold/pull/672) (use shutil, see their [patch](https://github.com/deepmind/alphafold/commit/0d9a24b284d39e0ccee9af34c66084e0c4297377)), this way our and their notebooks do not differ more than necessary. But I found this solution insuficient because it just avoids using %shell, leaving it broken. So I added the second commit which I think is superior to AlphaFold's fix (which can still stay there).

### CODE REVIEW

**Comment by vaclavhanzl** [comment]
You can test the fixed notebook in colab here:
https://colab.research.google.com/github/vaclavhanzl/openfold/blob/fix-colab-notebook/notebooks/OpenFold.ipynb

**Comment by vaclavhanzl** [comment]
I noticed that with relaxation off, protein is computed and shown but NOT saved to the downloaded zip. My third commit should fix this but I am not able to test it at the moment (Colab is not willing to lend me a free GPU just now and I'd like to test in the free mode). If somebody can test it, please do.

**Comment by vaclavhanzl** [comment]
Qusetion (@gahdritz ?): What was the idea behind conditional installation/import based on relax_prediction? Save time? Make it more robust? As I had to install openmm unconditionally (to get overwrite_b_factors from file depending on openmm), I guess I can as well install/import the rest unconditionally, too? Maybe the - now avoided - UTF-8 glitch was the reason to avoid openmm? Or did you intend to further refactor codebase to make openmm avoidable?

I might do another commit removing install/import dependencies on relax_prediction, then one could easily repeat just the last cell to get protein with relax and without.

**Comment by gahdritz** [comment]
Yeah it was initially intended to save time. Thanks for the PR!

**Pull request merged**
