### PR TITLE
fix incorrect learning rate warm-up after restarting from ckpt

### PR DESCRIPTION
**Pull request by Zhang690683220**
A simple fix to #181

### CODE REVIEW

**Comment by gahdritz** [comment]
Could you explain how this works? Where is `resume_last_lr_step` defined? When is `self.last_lr_step` ever assigned to anything except -1?

**Comment by Zhang690683220** [comment]
Oh, I forgot the definition of `resume_last_lr_step()`. It's added in the [69a8a28](https://github.com/aqlaboratory/openfold/pull/182/commits/69a8a28796e958323bbb4089d540aea4944fb706) commit.

**Comment by gahdritz** [comment]
One more thing: this assumes that the `resume_from_ckpt` is a ZERO checkpoint. You should add a quick check that the `resume_from_ckpt` argument is a directory and not a file.

**Comment by Zhang690683220** [comment]
The non deepspeed ckpt file is supported now.

**Pull request merged**
