### PR TITLE
Drop chains that are missing (structure) data in training

### PR DESCRIPTION
**Pull request by timodonnell**
This PR moves `chain_data_cache_paths` from `OpenFoldDataset` (where it was a list, one per dataset)  to a single string `chain_data_cache_path` in `OpenFoldSingleDataset`. This makes it convenient to drop entries (with a warning) where we have alignments but no structure data, instead of crashing.

The motivation here was that while trying to start a small training run, I was hitting an issue where a few chains were present in my alignment data (downloaded from RODA) but absent in my pdb_mmcif dir (downloaded from PDB via download_pdb_mmcif.sh). I see there is now `scripts/download_roda_pdbs.sh` to address this but I thought it might be good to be able handle this error a bit better anyway.

Curious if you think this makes sense @gahdritz 

I also note a few tests are failing for me here, but the same tests appear to be failing for me on `main` (basic inference and training seems to work). If you approve the PR I'd rather have you wait though to merge it so I can check more carefully it's not breaking anything.

### CODE REVIEW

**Comment by gahdritz** [comment]
Thanks Tim! I like the concept, but I think it might be a little bit more natural to look for matching structure files in the `OpenFoldSingleDataset`'s `data_dir` directly, rather than using the `chain_data_cache` as a proxy. While I can't think of a scenario where the `chain_data_cache` contains proteins that don't have accompanying structure files, it's a little confusing this way.

**Comment by timodonnell** [comment]
Thanks @gahdritz , that makes sense. I'll try the implementation you suggest. Separately, do you think `chain_data_cache` (or `_caches`) should live in `OpenFoldDataset` or `OpenFoldSingleDataset` ? It seemed cleaner to move it to `OpenFoldSingleDataset` but I wondering if I'm missing something

**Comment by gahdritz** [comment]
Wait hold on a second. This doesn't even break the use case I mentioned, right? If the chain_data_cache is a strict superset of the current training data, no chains are removed?

**Comment by timodonnell** [comment]
Yeah, I think anything that runs already would continue to work. Extra chains in the cache wouldn't cause a problem.

The only difference is that when chain_data_cache is missing chains that are in the alignment data, they will be dropped instead of causing a crash eventually in the training loop.

I think your suggestion to look at the actual cif files on disk also makes sense, since anything missing there would also cause a crash. This could be done in addition to the change here that just drops chains not present in the cache.

**Comment by gahdritz** [comment]
I actually prefer your original solution to what I suggested. Looking at the .cif files wouldn't give you anything about the chains in particular without re-parsing the .cif files, which defeats the point of having the `chain_data_cache`. I'll merge this as-is.

**Pull request merged**
